# Generated by Django 5.2.3 on 2025-06-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('idType_category', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID Category')),
                ('idType_number', models.CharField(max_length=100, unique=True, verbose_name='ID Number')),
                ('idType_desc', models.TextField(blank=True, null=True, verbose_name='ID Description')),
                ('idType_image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'ID Type',
                'verbose_name_plural': 'ID Types',
                'unique_together': {('idType_category', 'idType_number')},
            },
        ),
    ]
