# Generated by Django 5.2.3 on 2025-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250)),
                ('idCred_name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('idCred_addr', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('idCred_dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'ID Credential',
                'verbose_name_plural': 'ID Credentials',
            },
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_isexp',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
