# Generated by Django 5.2.4 on 2025-07-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_idcredentials_idtype_idtype_isexp_alter_idtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtype',
            name='idType_expdate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_issauth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Issuing Authority'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_issdate',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
    ]
