# Generated by Django 5.2.4 on 2025-08-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0002_idcredentials_idtype_idtype_isexp_alter_idtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtype',
            name='idType_expdate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_issauth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Issuing Authority'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_issdate',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_kind',
            field=models.CharField(choices=[('passport', 'Passport'), ('license', "Driver's License"), ('nationalid', 'National ID')], default='passport', max_length=20, verbose_name='ID Kind'),
        ),
        migrations.AddField(
            model_name='idtype',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_types', to='id.idcredentials', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='idType_number',
            field=models.CharField(max_length=101, unique=True, verbose_name='ID Number'),
        ),
    ]
