# Generated by Django 5.2.4 on 2025-07-16 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0004_remove_idtype_idtype_isexp_idcredentials_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idattachment',
            options={'verbose_name': 'ID Attachment', 'verbose_name_plural': 'ID Attachments'},
        ),
        migrations.AlterField(
            model_name='idattachment',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attachments', to='id.idtype'),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='idType_verify_stat',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
