# Generated by Django 5.2.5 on 2025-08-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0005_alter_idattachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcredentials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idtype',
            name='idType_verify_stat',
        ),
        migrations.RemoveField(
            model_name='idtype',
            name='user',
        ),
        migrations.AddField(
            model_name='idtype',
            name='idType_isexp',
            field=models.BooleanField(default=False, verbose_name='Expired'),
        ),
        migrations.AlterField(
            model_name='idtype',
            name='idType_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='IdAttachment',
        ),
    ]
