# Generated by Django 5.2.5 on 2025-08-13 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0006_remove_idcredentials_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idcredentials',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_types', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
