# Generated by Django 5.2.4 on 2025-07-15 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0003_idtype_idtype_expdate_idtype_idtype_issauth_and_more'),
    ]

    operations = [
    ]
